### ISSUE TITLE
Problem with new indentResolve stuff

### ISSUE THREAD

**Issue by devinus** [posthtml/posthtml-postcss#7]
I'm getting this error on many of my inputs now:

```RangeError: Invalid array length
    at indentResolve (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml-postcss/index.js:18:25)
    at /Users/devinus/Projects/rebelmail-templates/node_modules/posthtml-postcss/index.js:45:30
    at traverse (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:66:32)
    at traverse (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:72:8)
    at traverse (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:66:23)
    at traverse (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:72:8)
    at traverse (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:66:23)
    at Array.module.exports.walk (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/api.js:19:16)
    at posthtmlPostcss (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml-postcss/index.js:36:14)
    at err (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/posthtml.js:94:24)
    at tryCatch (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/posthtml.js:144:16)
    at PostHTML.<anonymous> (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/posthtml.js:93:32)
    at _next (/Users/devinus/Projects/rebelmail-templates/node_modules/posthtml/lib/posthtml.js:75:24)```

**Comment by devinus** [comment]
Could we disable/bypass this new stuff at all?

**Comment by devinus** [comment]
It actually significantly reduces our performance and we have to process a lot of documents.

**Comment by GitScrum** [comment]
@devinus show me please html page where you use inline styles. 
@voischev Thanks what ping me )

**Comment by GitScrum** [comment]
@devinus fix, you need update pkg.
